[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cuprush = "9u7uuj7S8kMon564b4TA8Gc7RaYXSC5QgjDz8fFgmGCU"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[hooks]
